export const TECH_STACK_OPTIONS = [
  // Frontend Frameworks & Libraries
  'ReactJS',
  'VueJS',
  'Vue.js',
  'Angular',
  'AngularJS',
  'Svelte',
  'SvelteKit',
  'NextJS',
  'NuxtJS',
  'Gatsby',
  'Remix',
  'Astro',
  'Solid.js',
  'Preact',
  'EmberJS',
  'BackboneJS',
  'jQuery',
  // State Management
  'Redux',
  'Zustand',
  'Jotai',
  'Recoil',
  'MobX',
  'Pinia',
  'Vuex',
  // Data Fetching
  'TanStack Query',
  'React Query',
  'SWR',
  'Apollo Client',
  'Axios',
  'Fetch API',
  // Backend & Runtime
  'NodeJS',
  'Deno',
  'Bun',
  'Express',
  'Fastify',
  'Koa',
  'NestJS',
  'tRPC',
  // Programming Languages
  'TypeScript',
  'JavaScript',
  'Python',
  'Java',
  'C++',
  'C#',
  'PHP',
  'Ruby',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'Dart',
  // Python Frameworks
  'Django',
  'Flask',
  'FastAPI',
  'Tornado',
  // Java Frameworks
  'Spring Boot',
  'Spring',
  'Hibernate',
  'Quarkus',
  // PHP Frameworks
  'Laravel',
  'Symfony',
  'CodeIgniter',
  // Ruby Frameworks
  'Ruby on Rails',
  'Sinatra',
  // Databases
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'SQLite',
  'Redis',
  'Elasticsearch',
  'Cassandra',
  'DynamoDB',
  'Firebase',
  'Supabase',
  'Neo4j',
  // ORMs & Database Tools
  'Prisma',
  'Sequelize',
  'TypeORM',
  'Mongoose',
  'Drizzle',
  // Cloud & DevOps
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'Vercel',
  'Netlify',
  'Cloudflare',
  'Terraform',
  'Jenkins',
  'GitLab CI',
  'GitHub Actions',
  'CircleCI',
  // Version Control
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  // APIs & Protocols
  'GraphQL',
  'REST API',
  'gRPC',
  'WebSocket',
  'Socket.io',
  'tRPC',
  // CSS Frameworks & Preprocessors
  'Tailwind CSS',
  'Bootstrap',
  'Material-UI',
  'Ant Design',
  'Chakra UI',
  'Styled Components',
  'Emotion',
  'Sass',
  'Less',
  'PostCSS',
  'CSS Modules',
  // Build Tools & Bundlers
  'Webpack',
  'Vite',
  'Rollup',
  'Parcel',
  'esbuild',
  'SWC',
  'Turbo',
  'Turborepo',
  'Nx',
  'pnpm',
  'Yarn',
  'npm',
  // Testing
  'Jest',
  'Vitest',
  'Mocha',
  'Cypress',
  'Playwright',
  'Testing Library',
  'React Testing Library',
  'Puppeteer',
  // Mobile Development
  'React Native',
  'Flutter',
  'Ionic',
  'Expo',
  // Desktop Development
  'Electron',
  'Tauri',
  // Other Tools & Technologies
  'Nginx',
  'Apache',
  'RabbitMQ',
  'Kafka',
  'Babel',
  'ESLint',
  'Prettier',
  'Storybook',
  'D3.js',
  'Chart.js',
  'Three.js',
  'WebGL',
  'PWA',
  'Microservices',
  'Serverless',
  'Lambda',
  'API Gateway',
  'CDN',
  'CI/CD'
];
